### ISSUE TITLE
[gitbit] update count of hosting services

### ISSUE THREAD

**Issue by waldyrious** [hplgit/hplgit.github.com#1]
"[four popular project hosting services](https://github.com/hplgit/hplgit.github.com/search?q="Four+popular"&type=Code)" should instead be "five popular project hosting services" instead, to match the list.

**Comment by hplgit** [comment]
Thanks for pointing this out!

**Comment by waldyrious** [comment]
No problem :) By the way, did you mean to close this or just comment? I can't find any commits fixing that and the live versions still contain the error.

**Comment by hplgit** [comment]
The source is in another repo, and now that source is recompiled and published on hplgit.github.io. It does not make sense to update anything by hand in this latter repo since it just has compiled files, but several files are now committed.

**Comment by waldyrious** [comment]
Ok, I figured the setup would probably be something like that, just making sure.
